name: Automated product release

on:
  pull_request:
    branches: [master]
    types: [closed]
  push:
    branches: [master]

jobs:
  publish:
    name: Publish package
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Checkout actions
        uses: actions/checkout@v4
      - name: Publish to NPM
        run: |
          yarn install
          yarn build
          cd lib
          npm publish --access public
          echo "OK"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
