name: Automated product release

on:
  pull_request:
    branches: [master]
    types: [closed]
  push:
    branches: [master]

jobs:
  publish:
    name: Publish package
    needs: check-release
    if: needs.check-release.outputs.release == 'true'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Publish to NPM
        run: |
          yarn build
          cd lib
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
